### ISSUE TITLE
Create list of departments and assign to individuals

### ISSUE THREAD

**Issue by lchski** [GoC-Spending/GoC-Spending#15]

**Comment by lchski** [comment]
Another one done!

The page is here: https://github.com/GoC-Spending/GoC-Spending/wiki/Departments-and-assignments

@toobs2017 and @souaaz, I’ve put your names beside the departments I believe you’re working on. Feel free to edit the wiki to correct/update anything!

**Comment by souaaz** [comment]
@lchski : OK. Will do.
