### ISSUE TITLE
Figure out number in “Description of work”

### ISSUE THREAD

**Issue by lchski** [GoC-Spending/GoC-Spending#18]
In TBS and PWSGC datasets. e.g. `421 - Architectural Services`, `1284- Client Software`, `665 - Other Equipment`, `656 - Heating, Air-Conditioning and Refrigeration Empt`.

**Comment by sboots** [comment]
PDF details here!

https://www.tpsgc-pwgsc.gc.ca/recgen/pceaf-gwcoa/1516/fichiers-files/7-2-eng.pdf

**Comment by lchski** [comment]
Fastest ticket closed!
