### ISSUE TITLE
Fix for contract amounts for the CSA

### ISSUE THREAD

**Issue by sboots** [GoC-Spending/GoC-Spending#19]
Note the commas - this is likely adding two orders of magnitude to CSA contracts.
http://www.asc-csa.gc.ca/eng/publications/contracts-details.asp?id=3332&trimestre=17&pg=

**Comment by nschonni** [comment]
Since they are using French currency formats, it can probably be detected by looking for the `$` on the right of the digit and then replacing the comma with a period
